#! /usr/bin/env python

from tkinter import *


class AskPass(Tk):

    def __init__(self, title, default_data='', *args, **kwargs):
        Tk.__init__(self, *args, **kwargs)
        self.data = default_data

        self.bind('<Return>', self._return)

        self.title(title)
        self.resizable(0, 0)

        self.frame = Frame(self, relief='raised', border=1, padx=3, pady=3)
        self.frame.pack(side='top', expand=True, fill=BOTH)

        self.entry = Entry(self.frame)
        self.entry.config(show='*')
        self.entry.pack(side='left', expand=True, fill=BOTH)
        self.entry.focus_set()

    def _return(self, event):
        self.data = self.entry.get()
        print(askpass.data)

        # Sort of a hack to avoid i3 bug with events.
        self.after(1, lambda: event.widget.quit())


if __name__ == '__main__':
    askpass = AskPass('Word Pass')
    askpass.mainloop()





